### ISSUE TITLE
[Request] Armor Stand intergration?

### ISSUE THREAD

**Issue by A5ho9999** [tr7zw/DisguiseHeads#1]
Is it possible to make the heads disguise armor stands with the player skin?

**Comment by tr7zw** [comment]
Huh, wasn't there already an open request for this? Anyway, it's planned yes.

**Comment by A5ho9999** [comment]
Awesome, can't wait

**Comment by Terraphice** [comment]
+1, since this seems relatively neglected and I feel it might help to express interest.
