### ISSUE TITLE
1.19.3?

### ISSUE THREAD

**Issue by Aces-and-Jacks** [tr7zw/DisguiseHeads#3]
Do you plan on updating the mod, and if it already works would you be able to mark it on modrinth?

**Comment by tr7zw** [comment]
Uhhh my last information was that the 1.19 version works for 1.19.3. Correct me if I'm wrong.

**Comment by Aces-and-Jacks** [comment]
unfortunately I wouldn't know how to test it. I just saw that on modrinth it didn't have the 1.19.3 tag, which then shows on the launcher I use as unavailable for that version. Minecraft loads when the mod is enabled

**Comment by tr7zw** [comment]
If the mod loads and works correctly, I can add the 1.19.3 tag on Modrinth/Curse. Honestly forgot about that.

**Comment by Aces-and-Jacks** [comment]
ok, thanks. Guess if someone else encounters a problem they'll report it

**Comment by tr7zw** [comment]
Gave it a quick test, seems to work. I set the 1.19.3 flag on the Fabric and Forge file on Modrinth and CurseForge.
