### ISSUE TITLE
Minime Pets file??

### ISSUE THREAD

**Issue by ChicknTurtle** [tr7zw/DisguiseHeads#5]
On curseforge the newest file for 1.20.1 is minime pets instead of disguiseheads for some reason.

<img width="1045" alt="image" src="https://github.com/tr7zw/DisguiseHeads/assets/72529982/96e7599a-179f-4681-8bc6-8740a0f1141e">

Just thought I should let you know.

**Comment by tr7zw** [comment]
Didnt I delete them? During the deploy, there was a copy-paste fail causing that.

**Comment by ChicknTurtle** [comment]
Guess not, because I can still see the file in the CurseForge app and website
https://www.curseforge.com/minecraft/mc-mods/disguiseheads/files/4910229

**Comment by tr7zw** [comment]
Archived/deleted more, apparently the new website doesn't display this correctly
![grafik](https://github.com/tr7zw/DisguiseHeads/assets/5133936/a75fb38a-df81-4953-841c-84d7605db805)

**Comment by tr7zw** [comment]
Buy yea, all wrong files are archived, reported the bug to curse.
