### ISSUE TITLE
1.20.2 Release

### ISSUE THREAD

**Issue by Terraphice** [tr7zw/DisguiseHeads#7]
I hate to be one of those people who make an issue specifically to ask for continued development, but...

I have been eagerly awaiting a 1.20.2 release, as that seems to be the sweet spot for mod releases/updates in the 1.20.X update series. (And subsequently, the version I have heavily modded on the client side for up-to-date vanilla MC.) I love small vanilla+ client side mods that make the experience just a little bit more featured, especially all of yours, and DisguiseHeads is one of my favorites in recent times. (I'm unsure if you remember, but I spoke to the ETF creator to get emissive player skin support w/ DisguiseHeads a while back because I like this mod so much!)

I was very content waiting, but as 1.20.3 and 1.20.4 have since released, I realized you may just forgo 1.20.2 and update the mod directly for 1.20.4 (or later), as it's the latest version. I wanted to ask whether you'd be releasing a 1.20.2 version, and show some interest in it. I know it's been a very long time since a release, and you're very likely to spend any time updating at this point straight to 1.20.4 and that's understandable.

I currently get Mixin errors with the latest release of the mod on 1.20.2, but if you do decide you're forgoing a 1.20.2 release, I'll see about updating the relevant versioning metadata and attempting to fix them for 1.20.2 myself for personal use regardless. Thanks for considering!

**Comment by tr7zw** [comment]
Oops looks like I skipped 1.20.2(current main branch is for 1.20.4). I don't remember if the 1.20.2 version already contained the PlayerSkin class logic, if so, it should be easy to add 1.20.2 later today too.
