### ISSUE TITLE
[Suggestion] Put Player Heads on Armor Stands to render the player model

### ISSUE THREAD

**Issue by floofyneko69** [tr7zw/DisguiseHeads#8]
This could work in a similar manner to MiniMePets, where the model for the armor stand is replaced with the associated model of the player head (As in whether it's 3 px or 4 px arms)

Would go great with map creations as the creators can use just armor stands and player heads to show who helped with the creation of the map!

**Comment by tr7zw** [comment]
Use the dev branch, this is already implemented.

**Comment by floofyneko69** [comment]
Oh? Where do I access the dev branch then?

**Comment by tr7zw** [comment]
Click on the Actions tab above, the top build, then at the bottom Artifacts. Get the correct jar that you need for your version. Make sure the Armorstand Disguise is turned on in the settings.

**Comment by tr7zw** [comment]
It's in the current release now.
